#!/bin/bash

# Clean Build Script for Android Whisper Project
# This script cleans all build artifacts and CMake cache to resolve build issues

echo "🧹 Cleaning Android Whisper project build..."

# Clean Gradle build cache
echo "📦 Cleaning Gradle build cache..."
./gradlew clean

# Remove .gradle cache directory
echo "📁 Removing .gradle cache..."
rm -rf .gradle

# Remove Android build directories
echo "📱 Removing Android build directories..."
rm -rf app/build
rm -rf build

# Remove CMake build cache
echo "🔧 Removing CMake build cache..."
rm -rf app/.cxx
rm -rf app/.externalNativeBuild

# Remove local.properties (will be regenerated by Android Studio)
echo "⚙️ Removing local.properties..."
rm -f local.properties

echo "✅ Build clean complete!"
echo ""
echo "Next steps:"
echo "1. Open project in Android Studio"
echo "2. Let it sync and generate local.properties"
echo "3. Build the project"
echo ""
echo "If you still get CMake errors, try:"
echo "• File → Invalidate Caches and Restart in Android Studio"
echo "• Check that Android NDK is properly installed"
echo "• Verify your SDK/NDK paths in Android Studio settings" 